// Copy the committed ATHAR OpenAPI contract into the frontend monorepo root.
// Source: backend repo (../Athar/docs/specs/openapi.json — regenerated by
// scripts/generate_openapi.py and CI-gated against drift).
import { copyFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const src = resolve(root, "../Athar/docs/specs/openapi.json");
const out = join(root, "openapi.json");

if (!existsSync(src)) {
  console.error(
    `openapi.json not found at ${src}\n` +
      "Generate it first: cd ../Athar && python scripts/generate_openapi.py",
  );
  process.exit(1);
}

mkdirSync(dirname(out), { recursive: true });
copyFileSync(src, out);
console.log(`Synced ${out}`);
