/**
 * Typed API client derived from the OpenAPI contract.
 *
 * `client` is an openapi-fetch instance whose path/param/response types come
 * from src/lib/api-types.ts (generated by `npm run generate:api` from the
 * backend's committed spec). Spec paths carry the `/api/v1/` prefix, so the
 * base URL is the API origin only.
 */
import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./api-types";
import { API_BASE_URL, USE_MOCK_API } from "./config";
import { ApiError } from "./api";
import { resolveMockPath } from "./mock-data";

export const API_ORIGIN = API_BASE_URL.replace(/\/api\/v1\/?$/, "");

const authMiddleware: Middleware = {
  async onRequest({ request }) {
    const token =
      typeof window === "undefined" ? null : localStorage.getItem("athar_access_token");
    if (token) request.headers.set("Authorization", `Bearer ${token}`);
    return request;
  },
};

/**
 * Mock resolver. In mock-first mode every resolvable GET is answered
 * immediately from the local dataset (no network wait — the backend isn't
 * ready yet). Otherwise it only kicks in `onError` as an offline fallback.
 * Mutations are never mocked — they surface the real network error.
 */
function mockBody(request: Request): Response | undefined {
  if (request.method !== "GET") return undefined;
  const url = new URL(request.url);
  const body = resolveMockPath(url.pathname, url.searchParams);
  if (body === undefined) return undefined;
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
}

const mockMiddleware: Middleware = {
  async onRequest({ request }) {
    if (!USE_MOCK_API) return undefined;
    return mockBody(request);
  },
  async onError({ request }) {
    return mockBody(request);
  },
};

export const client = createClient<paths>({
  baseUrl: API_ORIGIN,
});

client.use(authMiddleware, mockMiddleware);

/** Unwrap an openapi-fetch result, throwing ApiError on non-2xx (like apiFetch). */
export function unwrap<T>(res: {
  data?: T;
  error?: unknown;
  response: Response;
}): T {
  if (res.error) {
    throw new ApiError(
      `API ${res.response.status} ${res.response.url}`,
      res.response.status,
      res.error,
    );
  }
  if (res.data === undefined) {
    throw new ApiError(`API returned no data (${res.response.status})`, res.response.status);
  }
  return res.data;
}
