/**
 * Typed API client derived from the OpenAPI contract.
 *
 * `client` is an openapi-fetch instance whose path/param/response types come
 * from src/lib/api-types.ts (generated by `npm run generate:api` from the
 * backend's committed spec). Spec paths carry the `/api/v1/` prefix, so the
 * base URL is the API origin only.
 */
import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./api-types";
import { API_BASE_URL } from "./config";
import { ApiError } from "./api";

export const API_ORIGIN = API_BASE_URL.replace(/\/api\/v1\/?$/, "");

const authMiddleware: Middleware = {
  async onRequest({ request }) {
    const token =
      typeof window === "undefined" ? null : localStorage.getItem("athar_access_token");
    if (token) request.headers.set("Authorization", `Bearer ${token}`);
    return request;
  },
};

export const client = createClient<paths>({
  baseUrl: API_ORIGIN,
});

client.use(authMiddleware);

/** Unwrap an openapi-fetch result, throwing ApiError on non-2xx (like apiFetch). */
export function unwrap<T>(res: {
  data?: T;
  error?: unknown;
  response: Response;
}): T {
  if (res.error) {
    throw new ApiError(
      `API ${res.response.status} ${res.response.url}`,
      res.response.status,
      res.error,
    );
  }
  if (res.data === undefined) {
    throw new ApiError(`API returned no data (${res.response.status})`, res.response.status);
  }
  return res.data;
}
